/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLanguageToggle: typeof import('./../src/components/Application/AppLanguageToggle.vue')['default']
    AppLogo: typeof import('./../src/components/Application/AppLogo.vue')['default']
    AppProvider: typeof import('./../src/components/Application/AppProvider.vue')['default']
    AppThemeToggle: typeof import('./../src/components/Application/AppThemeToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    QrCode: typeof import('./../src/components/QrCode/QrCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StrengthCompute: typeof import('./../src/components/StrengthCompute/StrengthCompute.vue')['default']
  }
}
